---
abstract: 'Executable for App::mio'
author:
  - 'DBR <dbr@cpan.org>'
build_requires:
  Carp: 0
  ExtUtils::MakeMaker: 0
  File::Spec::Functions: 0
  List::Util: 0
  Module::Build: 0.3601
  Scalar::Util: 0
  Test::CheckDeps: 0.002
  Test::More: 0.94
  Test::UseAllModules: 0
  perl: 5.004
configure_requires:
  ExtUtils::MakeMaker: 6.30
  Module::Build: 0.3601
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300028, CPAN::Meta::Converter version 2.120921'
license: unrestricted
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: App-mio
provides:
  App::mio:
    file: lib/App/mio.pm
    version: v0.1.0
requires:
  FindBin: 0
  strict: 0
  warnings: 0
version: 0.1.0
x_authority: cpan:DBR
